use anyhow::{Context, Result};
use clap::Parser;
use regex::Regex;
use std::fs;
use std::path::PathBuf;

#[derive(Parser, Debug)]
#[command(author, version, about = "AArch64 Thunk Wrapper Auto-Generator from C Headers", long_about = None)]
struct Args {
    /// Input C header (.h) file path
    #[arg(short, long)]
    input: Option<PathBuf>,

    /// Output Rust file path for generated thunk functions
    #[arg(short, long)]
    output: Option<PathBuf>,

    /// Direct inline C header string input
    #[arg(long)]
    header_str: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CParam {
    pub name: String,
    pub c_type: String,
    pub is_pointer: bool,
}

#[derive(Debug, Clone, PartialEq)]
pub struct CFunction {
    pub name: String,
    pub return_type: String,
    pub params: Vec<CParam>,
}

/// AArch64 calling convention register name for argument index
fn aarch64_reg_name(idx: usize) -> &'static str {
    match idx {
        0 => "x0",
        1 => "x1",
        2 => "x2",
        3 => "x3",
        4 => "x4",
        5 => "x5",
        6 => "x6",
        7 => "x7",
        _ => "stack",
    }
}

/// System V x86_64 calling convention register name for argument index
fn x86_64_reg_name(idx: usize) -> &'static str {
    match idx {
        0 => "rdi",
        1 => "rsi",
        2 => "rdx",
        3 => "rcx",
        4 => "r8",
        5 => "r9",
        _ => "stack",
    }
}

pub fn parse_c_header(header_content: &str) -> Vec<CFunction> {
    // 1. Remove comments
    let re_block_comment = Regex::new(r"(?s)/\*.*?\*/").unwrap();
    let content = re_block_comment.replace_all(header_content, "");
    let re_line_comment = Regex::new(r"//.*").unwrap();
    let content = re_line_comment.replace_all(&content, "");

    // 2. Strip GCC / Clang attributes & glibc specifiers
    let re_attr = Regex::new(r"__attribute__\s*\(\(.*?\)\)").unwrap();
    let content = re_attr.replace_all(&content, "");
    let re_nonnull = Regex::new(r"__nonnull\s*\(\(.*?\)\)").unwrap();
    let content = re_nonnull.replace_all(&content, "");
    let re_macros = Regex::new(r"\b(__THROW|__THROWNL|__leaf|__restrict|__const|__wur|__warnattr\([^)]*\))\b").unwrap();
    let content = re_macros.replace_all(&content, "");

    let mut functions = Vec::new();

    // 2. Match C function declarations: e.g., int add(int a, int b);
    let re_fn = Regex::new(r"(?m)^\s*(?:extern\s+)?([A-Za-z0-9_][A-Za-z0-9_\*\s]*?\b)\s*([\*]*[A-Za-z0-9_]+)\s*\(([^)]*)\)\s*;").unwrap();

    for cap in re_fn.captures_iter(&content) {
        let mut ret_type = cap[1].trim().to_string();
        let mut fn_name = cap[2].trim().to_string();
        let raw_params = cap[3].trim();

        if fn_name.starts_with('*') {
            let stars = fn_name.chars().take_while(|c| *c == '*').count();
            ret_type.push_str(&" *".repeat(stars));
            fn_name = fn_name[stars..].to_string();
        }

        if ret_type.starts_with('#') || fn_name.starts_with('#') {
            continue;
        }

        let mut params = Vec::new();
        if !raw_params.is_empty() && raw_params != "void" {
            for param_str in raw_params.split(',') {
                let p = param_str.trim();
                if p.is_empty() {
                    continue;
                }
                let is_pointer = p.contains('*');
                let parts: Vec<&str> = p.split_whitespace().collect();
                let (c_type, name) = if parts.len() >= 2 {
                    let raw_name = parts.last().unwrap();
                    let clean_name = raw_name.split('[').next().unwrap().trim_matches(|c: char| !c.is_alphanumeric() && c != '_');
                    let name = if clean_name.is_empty() {
                        format!("arg{}", params.len())
                    } else {
                        clean_name.to_string()
                    };
                    let c_type = parts[..parts.len() - 1].join(" ");
                    (c_type, name)
                } else {
                    (p.to_string(), format!("arg{}", params.len()))
                };

                params.push(CParam {
                    name,
                    c_type,
                    is_pointer,
                });
            }
        }

        functions.push(CFunction {
            name: fn_name,
            return_type: ret_type,
            params,
        });
    }

    functions
}

pub fn generate_rust_thunks(functions: &[CFunction]) -> String {
    use std::collections::HashSet;
    let mut seen = HashSet::new();
    let unique_funcs: Vec<&CFunction> = functions
        .iter()
        .filter(|f| seen.insert(f.name.clone()))
        .collect();

    let mut code = String::new();
    code.push_str("// Auto-generated by maarch64-thunk-gen. DO NOT EDIT MANUALLY.\n");
    code.push_str("use maarch64_core::{cpu::CpuContext, memory::MemoryManager};\n");
    code.push_str("use crate::ThunkManager;\n\n");

    // Generator registration function
    code.push_str("pub fn register_generated_thunks(manager: &mut ThunkManager) {\n");
    for f in &unique_funcs {
        code.push_str(&format!(
            "    manager.register_thunk(\"{}\", thunk_{});\n",
            f.name, f.name
        ));
    }
    code.push_str("}\n\n");

    // Generator individual thunk handlers
    for f in &unique_funcs {
        code.push_str(&format!(
            "/// Thunk wrapper for `{}` ({})\n",
            f.name,
            f.params
                .iter()
                .map(|p| format!("{} {}", p.c_type, p.name))
                .collect::<Vec<_>>()
                .join(", ")
        ));
        if f.name.contains("__") || f.name.chars().any(|c| c.is_uppercase()) {
            code.push_str("#[allow(non_snake_case)]\n");
        }
        code.push_str(&format!(
            "pub fn thunk_{}(ctx: &mut CpuContext, _mem: &mut MemoryManager) -> Result<(), String> {{\n",
            f.name
        ));
        code.push_str(&format!(
            "    // AArch64 -> x86_64 Register Copy / Marshalling for {}\n",
            f.name
        ));

        for (i, p) in f.params.iter().enumerate() {
            let aarch64_reg = aarch64_reg_name(i);
            let x86_reg = x86_64_reg_name(i);

            code.push_str(&format!(
                "    // Parameter {}: {} {} | Copy guest {} ({}) -> host {}\n",
                i, p.c_type, p.name, aarch64_reg, aarch64_reg.to_uppercase(), x86_reg.to_uppercase()
            ));

            let var_name = if p.name.starts_with('_') { p.name.clone() } else { format!("_{}", p.name) };
            if p.is_pointer && (p.c_type.contains("char") || p.c_type.contains("int8")) {
                code.push_str(&format!(
                    "    let {}_ptr = ctx.get_x({}); // {} -> {}\n",
                    var_name, i, aarch64_reg, x86_reg
                ));
            } else {
                code.push_str(&format!(
                    "    let {} = ctx.get_x({}); // {} -> {}\n",
                    var_name, i, aarch64_reg, x86_reg
                ));
            }
        }

        // Return value handling
        if f.return_type != "void" {
            code.push_str(&format!(
                "    // Call host function or stub and return result to guest x0 (RAX -> X0)\n"
            ));
            code.push_str("    let ret_val = 0u64; // Host call placeholder\n");
            code.push_str("    ctx.set_x(0, ret_val);\n");
        } else {
            code.push_str("    // Void return type\n");
        }

        code.push_str("    Ok(())\n");
        code.push_str("}\n\n");
    }

    code
}

fn main() -> Result<()> {
    let args = Args::parse();

    let header_content = if let Some(path) = &args.input {
        fs::read_to_string(path).with_context(|| format!("Failed to read file: {:?}", path))?
    } else if let Some(s) = &args.header_str {
        s.clone()
    } else {
        println!("No input header provided. Usage: maarch64-thunk-gen --input <header.h> --output <output.rs>");
        return Ok(());
    };

    let funcs = parse_c_header(&header_content);
    println!("Parsed {} C functions from header.", funcs.len());
    for f in &funcs {
        println!("  - {} {}({} params)", f.return_type, f.name, f.params.len());
    }

    let generated_code = generate_rust_thunks(&funcs);

    if let Some(out_path) = &args.output {
        fs::write(out_path, &generated_code).with_context(|| format!("Failed to write output to {:?}", out_path))?;
        println!("Generated thunk code written to {:?}", out_path);
    } else {
        println!("\nGenerated Code:\n{}", generated_code);
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_c_header_basic() {
        let header = r#"
            /* Sample C Header */
            int add(int a, int b);
            void *memcpy(void *dest, const void *src, size_t n);
            void cleanup(void);
        "#;
        let funcs = parse_c_header(header);
        assert_eq!(funcs.len(), 3);

        assert_eq!(funcs[0].name, "add");
        assert_eq!(funcs[0].return_type, "int");
        assert_eq!(funcs[0].params.len(), 2);
        assert_eq!(funcs[0].params[0].name, "a");
        assert_eq!(funcs[0].params[1].name, "b");

        assert_eq!(funcs[1].name, "memcpy");
        assert_eq!(funcs[1].params.len(), 3);
        assert!(funcs[1].params[0].is_pointer);

        assert_eq!(funcs[2].name, "cleanup");
        assert_eq!(funcs[2].params.len(), 0);
    }

    #[test]
    fn test_generate_rust_thunks() {
        let funcs = vec![CFunction {
            name: "puts".to_string(),
            return_type: "int".to_string(),
            params: vec![CParam {
                name: "s".to_string(),
                c_type: "const char*".to_string(),
                is_pointer: true,
            }],
        }];
        let code = generate_rust_thunks(&funcs);
        assert!(code.contains("pub fn thunk_puts"));
        assert!(code.contains("x0 (X0) -> host RDI"));
        assert!(code.contains("ctx.get_x(0)"));
    }
}
