[package]
name = "maarch64-runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "CLI executable runner for AArch64 binaries under Maarch64"

[[bin]]
name = "maarch64"
path = "src/main.rs"

[dependencies]
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
maarch64-core = { path = "../../core" }
maarch64-thunks = { path = "../../thunks" }
